function el(tag,className,text,field){const n=document.createElement(tag);if(className)n.className=className;if(text)n.textContent=text;if(field)n.dataset.editField=field;return n}
function heroDefault(c){const r=el('section','component hero');r.append(el('p','eyebrow',c.eyebrow,'eyebrow'),el('h1','',c.heading,'heading'),el('p','lede',c.body,'body'),el('a','button',c.actionLabel,'actionLabel'));return r}
function heroSplit(c){const r=el('section','component hero hero-split'),copy=el('div','variant-copy'),art=el('div','variant-art','N');copy.append(el('p','eyebrow',c.eyebrow,'eyebrow'),el('h1','',c.heading,'heading'),el('p','lede',c.body,'body'),el('a','button',c.actionLabel,'actionLabel'));r.append(copy,art);return r}
function heroEditorial(c){const r=el('section','component hero hero-editorial');r.append(el('p','eyebrow',c.eyebrow,'eyebrow'),el('div','rule'),el('h1','',c.heading,'heading'),el('div','editorial-foot'));r.lastChild.append(el('p','lede',c.body,'body'),el('a','text-link',c.actionLabel+' →','actionLabel'));return r}
function servicesGrid(c){const r=el('section','component services');r.append(el('p','eyebrow','What we do'),el('h2','',c.heading,'heading'));const grid=el('div','service-grid');c.items.forEach((item,i)=>{const card=el('article','service-card');card.append(el('h3','',item.title,`items.${i}.title`),el('p','',item.body,`items.${i}.body`));grid.append(card)});r.append(grid);return r}
function servicesList(c){const r=el('section','component services services-list');r.append(el('p','eyebrow','Capabilities'),el('h2','',c.heading,'heading'));const list=el('div','service-list');c.items.forEach((item,i)=>{const row=el('article','service-row');row.append(el('span','service-number',String(i+1).padStart(2,'0')),el('h3','',item.title,`items.${i}.title`),el('p','',item.body,`items.${i}.body`));list.append(row)});r.append(list);return r}
function ctaDefault(c){const r=el('section','component cta'),copy=el('div');copy.append(el('h2','',c.heading,'heading'),el('p','',c.body,'body'));r.append(copy,el('a','button button-secondary',c.actionLabel,'actionLabel'));return r}
const textFields=[{path:'heading',label:'Heading'},{path:'body',label:'Body',multiline:true},{path:'actionLabel',label:'Button label'}];
export const componentDefinitions=[
 {type:'hero',name:'Hero',defaultVariantId:'default',defaultContent:{eyebrow:'A strong first impression',heading:'Your next chapter starts here.',body:'Introduce the promise your customers care about most.',actionLabel:'Get started'},editableFields:[{path:'eyebrow',label:'Eyebrow'},...textFields],variants:[{id:'default',name:'Centered statement',render:heroDefault},{id:'split',name:'Split feature',render:heroSplit},{id:'editorial',name:'Editorial lead',render:heroEditorial}]},
 {type:'services',name:'Services',defaultVariantId:'cards',defaultContent:{heading:'How we can help',items:[{title:'Focused service',body:'Describe the outcome this service makes possible.'},{title:'Practical support',body:'Show how your team helps customers move forward.'},{title:'Lasting value',body:'Connect the work to a meaningful result.'}]},editableFields:[{path:'heading',label:'Heading'},{path:'items.0.title',label:'First service title'},{path:'items.0.body',label:'First service description',multiline:true}],variants:[{id:'cards',name:'Card grid',render:servicesGrid},{id:'list',name:'Editorial list',render:servicesList}]},
 {type:'cta',name:'Call to action',defaultVariantId:'default',defaultContent:{heading:'Ready to begin?',body:'Take the next clear step with our team.',actionLabel:'Start a conversation'},editableFields:textFields,variants:[{id:'default',name:'Banner',render:ctaDefault}]}
];
