const provenance={source:'rally-studio-seed',kind:'curated-default'};
export const librarySeeds=[
 {id:'component.hero',type:'component',name:'Hero',status:'certified',version:'1.0.0',tags:['marketing','intro'],description:'Primary page introduction component.',provenance,payload:{definitionType:'hero'}},{id:'component.services',type:'component',name:'Services',status:'certified',version:'1.0.0',tags:['marketing','services'],description:'Structured service offering component.',provenance,payload:{definitionType:'services'}},{id:'component.cta',type:'component',name:'Call to action',status:'certified',version:'1.0.0',tags:['marketing','conversion'],description:'Focused conversion prompt.',provenance,payload:{definitionType:'cta'}},
 {id:'token.color.primary',type:'token',name:'Primary color token',status:'certified',version:'1.0.0',tags:['design','color'],description:'Project primary color reference.',provenance,payload:{tokenPath:'designSettings.primaryColor'}},
 {id:'composition.service-home',type:'composition',name:'Service Business Home Core',status:'certified',version:'1.0.0',tags:['page','services'],description:'Hero, Services, and CTA for a service business home page.',provenance,payload:{executable:true,members:[{definitionType:'hero',content:{eyebrow:'Expert help, clearly delivered'}},{definitionType:'services'},{definitionType:'cta',content:{heading:'Build your next chapter'}}]}},
 {id:'composition.lead-intro',type:'composition',name:'Lead Generation Intro',status:'certified',version:'1.0.0',tags:['page','lead-generation'],description:'Split Hero and CTA for a focused campaign introduction.',provenance,payload:{executable:true,members:[{definitionType:'hero',variantId:'split',content:{heading:'Turn attention into momentum.'}},{definitionType:'cta'}]}},
 {id:'page-template.service-home',type:'composition',name:'Service Business Home',status:'certified',version:'1.0.0',tags:['page-template','home','services'],description:'A complete service-business landing page with introduction, offerings, and conversion.',provenance,payload:{kind:'page-template',executable:true,defaultPageName:'Home',members:[{compositionId:'composition.service-home'}]}},
 {id:'page-template.company-story',type:'composition',name:'Company Story',status:'certified',version:'1.0.0',tags:['page-template','about','story'],description:'An About page combining a focused introduction with a supporting services story.',provenance,payload:{kind:'page-template',executable:true,defaultPageName:'About',members:[{compositionId:'composition.lead-intro'},{definitionType:'services',variantId:'list',content:{heading:'How we got here'}}]}},
 {id:'page-template.lead-capture',type:'composition',name:'Lead Capture',status:'certified',version:'1.0.0',tags:['page-template','contact','conversion'],description:'A concise Contact page with a direct introduction and conversion action.',provenance,payload:{kind:'page-template',executable:true,defaultPageName:'Contact',members:[{definitionType:'hero',variantId:'split',content:{eyebrow:'Let’s talk',heading:'Start a conversation.'}},{definitionType:'cta',content:{heading:'Tell us what comes next',actionLabel:'Get in touch'}}]}},
 {id:'blueprint.lead-generation',type:'blueprint',name:'Lead generation blueprint',status:'experimental',version:'0.1.0',tags:['strategy'],description:'Non-executable blueprint example.',provenance,payload:{purpose:'lead-generation'}},{id:'starter.consulting',type:'starter-package',name:'Consulting foundation',status:'specialty',version:'0.1.0',tags:['consulting'],description:'Non-executable starter example.',provenance,payload:{compositionIds:['composition.service-home']}},{id:'token.legacy-accent',type:'token',name:'Legacy accent token',status:'deprecated',version:'0.8.0',tags:['legacy'],description:'Retained compatibility token.',provenance:{source:'studio-v3',kind:'legacy-reference'},payload:{tokenPath:'legacy.accent'}},{id:'composition.archive-demo',type:'composition',name:'Archived campaign page',status:'archived',version:'0.4.0',tags:['archive'],description:'Archived catalog example.',provenance:{source:'studio-v3',kind:'legacy-reference'},payload:{executable:false}}
];
