const clone=value=>structuredClone(value);
const domainTargets=new Set(['website','discovery','strategy','recommendations','packet','review','tasks']);

// Navigation is transient. Every handoff re-resolves authoritative Project/source identity.
export function createOperationsContext({projectStore,taskStore,conversationStore,reviewSessionStore}){
  let context={surface:'home',projectId:null,organizationId:null,websiteId:null,origin:'home',referenceId:null};
  const listeners=new Set(),notify=()=>listeners.forEach(fn=>fn(api.get()));
  function projectContext(projectId){const summary=projectStore.summary(projectId);return{summary,project:summary.project};}
  const api={get(){return clone(context);},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},overview(surface='home'){if(!['home','projects','queue','team'].includes(surface))throw new Error('Unknown operations surface');context={...context,surface};notify();},organization(organizationId){context={...context,surface:'organization',organizationId,projectId:null,websiteId:null,referenceId:null};notify();},project(projectId,{origin=context.origin}={}){const {project,summary}=projectContext(projectId);context={surface:'project',projectId,organizationId:project.organizationId,websiteId:summary.references.website?project.websiteId:null,origin,referenceId:null};notify();return api.get();},source(action){if(!context.projectId)throw new Error('Open a Project before entering its Website workflow');const {project,summary}=projectContext(context.projectId);if(!domainTargets.has(action.target))throw new Error('Unsupported Project target');if(!summary.references.website)throw new Error('This Project has no available Website. Inspect setup in Project.');if(['discovery','strategy'].includes(action.target)){const reference=summary.references[action.target],expectedId=action.target==='discovery'?project.discoveryResponseSetId:project.strategyId;if(!reference||!expectedId||(action.referenceId&&action.referenceId!==expectedId))throw new Error(`${action.target} reference is unavailable for this Project`);}if(action.target==='tasks'&&action.referenceId){const task=taskStore.get(action.referenceId);if(task.websiteId!==project.websiteId||!task.sourceState.available)throw new Error('Task source context is unavailable for this Project');}if(action.target==='review'&&action.referenceId){if(action.kind==='unresolved-conversation'){const item=conversationStore.get(action.referenceId);if(item.websiteId!==project.websiteId||!item.anchorState.available)throw new Error('Conversation context is unavailable for this Project');}else{const item=reviewSessionStore.get(action.referenceId);if(item.websiteId!==project.websiteId)throw new Error('Review belongs to another Website');}}context={...context,surface:'website',websiteId:project.websiteId,referenceId:action.referenceId||null};notify();return api.get();},directWebsite(){context={surface:'website',projectId:null,organizationId:null,websiteId:null,origin:'home',referenceId:null};notify();},returnProject(){if(!context.projectId)return null;const id=context.projectId;api.project(id);return id;}};
  return api;
}

export function ownershipLabel(teamStore,ownerId,{suggested=false}={}){if(!ownerId)return'Unassigned';const member=teamStore.get(ownerId);return`${suggested?'Suggested (Project default)':'Assigned'}: ${member.name}${member.status==='archived'?' — archived; reassign on source record':''}`;}

export function deriveOperationsHome({projectStore,queue,workloads}){const projects=projectStore.list().filter(item=>item.project.status==='active'),items=queue.list().filter(item=>item.status!=='unavailable'&&item.status!=='waiting-on-client');return{activeProjects:projects.length,blockedProjects:projects.filter(item=>item.attention.some(value=>value.severity==='blocking')||item.phase==='setup').length,total:items.length,high:items.filter(item=>item.priority==='high').length,topItems:items.slice(0,5),workloads:workloads.list().filter(item=>item.member.status==='active'||item.openTasks.length||item.readyCheckpoints.length)};}
