const clone=value=>structuredClone(value);
const STATUSES=Object.freeze(['active','on-hold','completed','archived']);
const actor=id=>({id:id||'local-user',name:id==='rally-staff'?'Rally staff':'Local user'});

export function createProjectStore(dependencies,{seed=true}={}){
  const {documentStore,discoveryStore,strategyStore,recommendationStore,reviewSessionStore,conversationStore,taskStore,organizationStore,teamStore}=dependencies;
  let projects={},order=[],selectedId=null,sequence=0;const listeners=new Set(),notify=()=>listeners.forEach(listener=>listener(api.getState()));
  const project=id=>{const value=projects[id];if(!value)throw new Error(`Unknown Project: ${id}`);return value;};
  const assertOrganization=id=>{if(!id)throw new Error('Project Organization is required');organizationStore?.getOrganization(id);};
  const resolve=id=>{const value=project(id),document=documentStore.getState(),website=value.websiteId===document.website.id?document.website:null,stateConversations=conversationStore.getState(),stateTasks=taskStore.getState(),discovery=website&&value.discoveryResponseSetId?tryGet(discoveryStore,value.discoveryResponseSetId):null,strategy=website&&value.strategyId?tryGet(strategyStore,value.strategyId):null;return{website,discovery,strategy,recommendations:website?recommendationStore.list().filter(item=>item.websiteId===value.websiteId):[],reviews:website?reviewSessionStore.listCurrentWebsite().filter(item=>item.websiteId===value.websiteId).map(item=>reviewSessionStore.get(item.id)):[],conversations:website?stateConversations.order.map(key=>stateConversations.conversations[key]).filter(item=>item.websiteId===value.websiteId):[],tasks:website?stateTasks.order.map(key=>stateTasks.tasks[key]).filter(item=>item.websiteId===value.websiteId):[]};};
  function tryGet(store,id){try{return store.get(id);}catch{return null;}}
  const derive=id=>{const value=project(id),references=resolve(id);if(!value.websiteId||!references.website)return setupSummary(value,references);const unresolved=references.conversations.filter(item=>item.status!=='resolved'),blocked=references.tasks.filter(item=>item.status==='blocked'),stale=references.recommendations.filter(item=>item.status==='stale'),activeReview=references.reviews.find(item=>item.status==='active'),approvedReview=references.reviews.find(item=>item.currentApproval),attention=[];
    if(!references.discovery)attention.push(attentionItem('missing-discovery','Discovery reference unavailable','discovery'));if(!references.strategy)attention.push(attentionItem('missing-strategy','Strategy reference unavailable','strategy'));for(const key of references.strategy?.staleFields||[])attention.push({...attentionItem('stale-strategy',`Strategy input update available: ${key}`,'strategy','attention'),referenceId:key});for(const item of stale)attention.push({...attentionItem('stale-recommendation',`Stale recommendation: ${item.title}`,'recommendations','attention'),referenceId:item.id});for(const item of unresolved)attention.push({...attentionItem('unresolved-conversation',item.messages[0]?.body||'Unresolved conversation','review',item.status==='waiting-on-rally'?'blocking':'attention'),referenceId:item.id});for(const item of blocked)attention.push({...attentionItem('blocked-task',item.title,'tasks'),referenceId:item.id});if(activeReview&&!activeReview.questionnaireSummary.requiredComplete)attention.push({...attentionItem('review-questions','Required review questions remain','review'),referenceId:activeReview.id});if(activeReview?.summary.ready&&activeReview.questionnaireSummary.requiredComplete&&!activeReview.currentApproval)attention.push({...attentionItem('awaiting-approval','Review is ready for approval','review','attention'),referenceId:activeReview.id});
    let phase='build';if(approvedReview)phase='approved';else if(activeReview||references.reviews.length)phase='review';else if(references.discovery?.progress.state!=='completed')phase='discovery';else if(references.strategy?.progress.state!=='ready')phase='strategy';else if(!references.recommendations.length||references.recommendations.some(item=>['proposed','stale'].includes(item.status)))phase='recommendations';const nextAction=deriveAction(value,phase,{stale,activeReview,approvedReview});return{project:clone(value),references,phase,nextAction,attention,counts:{tasks:references.tasks.length,blockedTasks:blocked.length,unresolvedConversations:unresolved.length,recommendations:references.recommendations.length,reviews:references.reviews.length}};};
  const api={statuses:STATUSES,subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);},getState(){return{projects:clone(projects),order:[...order],selectedId};},get(id){return clone(project(id));},list({organizationId,includeArchived=true}={}){return order.map(id=>api.summary(id)).filter(item=>(!organizationId||item.project.organizationId===organizationId)&&(includeArchived||item.project.status!=='archived'));},resolve,summary:derive,select(id){project(id);selectedId=id;notify();},create({organizationId,name,websiteId=null,discoveryResponseSetId=null,strategyId=null,ownerId=null,description='',createdBy='rally-staff',id}){assertOrganization(organizationId);if(ownerId!==null){if(!teamStore)throw new Error('Team store is required');teamStore.validateAssignment(ownerId);}const label=String(name||'').trim();if(!label)throw new Error('Project name is required');if(websiteId)api.assertWebsiteAvailable(websiteId);const identity=id||`project-${Date.now().toString(36)}-${++sequence}`,now=new Date().toISOString();if(projects[identity])throw new Error(`Project identity already exists: ${identity}`);projects[identity]={id:identity,organizationId,name:label,description:String(description),status:'active',ownerId,websiteId,discoveryResponseSetId,strategyId,createdAt:now,updatedAt:now,createdBy:actor(createdBy)};order.push(identity);selectedId=identity;notify();return identity;},setOwner(id,ownerId){const value=project(id);if(!teamStore)throw new Error('Team store is required');teamStore.validateAssignment(ownerId,value.ownerId);return update(value,{ownerId});},setStatus(id,status){if(!STATUSES.includes(status))throw new Error(`Unsupported Project status: ${status}`);return update(project(id),{status});},setOrganization(id,organizationId){assertOrganization(organizationId);return update(project(id),{organizationId});},assertWebsiteAvailable(websiteId,{exceptProjectId}={}){const conflict=order.map(id=>projects[id]).find(item=>item.id!==exceptProjectId&&item.websiteId===websiteId&&item.status!=='archived');if(conflict)throw new Error(`Website is already assigned to active Project: ${conflict.name}`);return true;},assignWebsite(id,websiteId,{confirmReplacement=false,discoveryResponseSetId=null,strategyId=null}={}){const value=project(id);if(!websiteId)throw new Error('Website identity is required');if(value.websiteId&&value.websiteId!==websiteId&&!confirmReplacement)throw new Error('Website reassignment requires explicit confirmation');api.assertWebsiteAvailable(websiteId,{exceptProjectId:id});return update(value,{websiteId,discoveryResponseSetId,strategyId});},unassignWebsite(id,{confirm=false}={}){const value=project(id);if(value.websiteId&&!confirm)throw new Error('Website unassignment requires explicit confirmation');return update(value,{websiteId:null,discoveryResponseSetId:null,strategyId:null});}};
  function update(value,changes){Object.assign(value,changes,{updatedAt:new Date().toISOString()});notify();return clone(value);}
  if(seed){const document=documentStore.getState(),discoveryResponseSetId=discoveryStore.ensureCurrent(),strategyId=strategyStore.ensureCurrent();api.create({id:'project-northstar',organizationId:'organization-northstar',name:'Northstar Advisory Website',description:'Studio 4 working Website project.',websiteId:document.website.id,discoveryResponseSetId,strategyId});api.create({id:'project-summit',organizationId:'organization-summit',name:'Summit Works Website',description:'Operational Project shell awaiting Website assignment.'});api.select('project-northstar');}
  return api;
}

function attentionItem(kind,label,target,severity='blocking'){return{kind,label,target,severity};}
function setupSummary(value,references){const unavailable=!!value.websiteId,nextAction=['on-hold','archived'].includes(value.status)?{kind:'paused',label:value.status==='archived'?'Project archived':'Project on hold',reason:'Resume the Project lifecycle before continuing operational work.',target:'project',priority:'normal'}:{kind:'assign-website',label:'Assign Website',reason:unavailable?'The assigned Website is unavailable in this runtime.':'This Project shell does not have a Website yet.',target:'project',priority:'blocking'};return{project:clone(value),references,phase:'setup',nextAction,attention:[attentionItem(unavailable?'unavailable-website':'unassigned-website',unavailable?'Website context unavailable':'Website unassigned','project')],counts:{tasks:0,blockedTasks:0,unresolvedConversations:0,recommendations:0,reviews:0}};}
function deriveAction(value,phase,{stale,activeReview,approvedReview}){if(['on-hold','archived'].includes(value.status))return{kind:'paused',label:value.status==='archived'?'Project archived':'Project on hold',reason:'Resume the Project lifecycle before continuing operational work.',target:'project',priority:'normal'};if(phase==='discovery')return{kind:'complete-discovery',label:'Complete Discovery',reason:'Required Discovery answers remain.',target:'discovery',referenceId:value.discoveryResponseSetId,priority:'high'};if(phase==='strategy')return{kind:'resolve-strategy',label:'Resolve Strategy decisions',reason:'Strategy is not ready for downstream work.',target:'strategy',referenceId:value.strategyId,priority:'high'};if(phase==='recommendations')return{kind:'review-recommendations',label:stale.length?'Refresh recommendations':'Review recommendations',reason:stale.length?'Strategy or Discovery inputs changed.':'Strategy is ready for recommendations.',target:'recommendations',priority:'high'};if(phase==='review'){if(activeReview?.summary.unresolved)return{kind:'resolve-review-conversations',label:'Resolve review conversations',reason:`${activeReview.summary.unresolved} conversation${activeReview.summary.unresolved===1?'':'s'} remain unresolved.`,target:'review',referenceId:activeReview.id,priority:'high'};if(activeReview&&!activeReview.questionnaireSummary.requiredComplete)return{kind:'complete-review-questions',label:'Complete required review questions',reason:'Approval evidence is incomplete.',target:'review',referenceId:activeReview.id,priority:'high'};if(activeReview&&!activeReview.currentApproval)return{kind:'approve-website',label:'Approve Website',reason:'The active review is ready for an explicit approval decision.',target:'review',referenceId:activeReview.id,priority:'high'};return{kind:'start-review',label:'Start Review',reason:'A formal review is the next operational checkpoint.',target:'review',priority:'normal'};}if(phase==='approved')return{kind:'approved',label:'Website approved',reason:'The current Review checkpoint has explicit approval.',target:'review',referenceId:approvedReview.id,priority:'normal'};return{kind:'continue-build',label:'Continue Website editing',reason:'Applied decisions are ready for Website work and review preparation.',target:'website',priority:'normal'};}
