const clone=value=>structuredClone(value);
const STATUSES=Object.freeze(['active','on-hold','completed','archived']);
const actor=id=>({id:id||'local-user',name:id==='rally-staff'?'Rally staff':'Local user'});

export function createProjectStore({documentStore,discoveryStore,strategyStore,recommendationStore,reviewSessionStore,conversationStore,taskStore},{seed=true}={}){
  let projects={},order=[],selectedId=null,sequence=0;const listeners=new Set(),notify=()=>listeners.forEach(listener=>listener(api.getState()));
  const project=id=>{const value=projects[id];if(!value)throw new Error(`Unknown Project: ${id}`);return value;};
  const websiteConversations=websiteId=>{const state=conversationStore.getState();return state.order.map(id=>state.conversations[id]).filter(item=>item.websiteId===websiteId);};
  const websiteTasks=websiteId=>{const state=taskStore.getState();return state.order.map(id=>state.tasks[id]).filter(item=>item.websiteId===websiteId);};
  const resolve=id=>{const value=project(id),document=documentStore.getState(),website=value.websiteId===document.website.id?document.website:null,discovery=value.discoveryResponseSetId?(()=>{try{return discoveryStore.get(value.discoveryResponseSetId);}catch{return null;}})():null,strategy=value.strategyId?(()=>{try{return strategyStore.get(value.strategyId);}catch{return null;}})():null,recommendations=recommendationStore.list().filter(item=>item.websiteId===value.websiteId),reviews=reviewSessionStore.listCurrentWebsite().filter(item=>item.websiteId===value.websiteId).map(item=>reviewSessionStore.get(item.id)),conversations=websiteConversations(value.websiteId),tasks=websiteTasks(value.websiteId);return{website,discovery,strategy,recommendations,reviews,conversations,tasks};};
  const derive=id=>{const value=project(id),references=resolve(id),unresolvedConversations=references.conversations.filter(item=>item.status!=='resolved'),blockedTasks=references.tasks.filter(item=>item.status==='blocked'),staleRecommendations=references.recommendations.filter(item=>item.status==='stale'),activeReview=references.reviews.find(item=>item.status==='active'),approvedReview=references.reviews.find(item=>item.currentApproval),attention=[];
    if(!references.website)attention.push({kind:'missing-website',label:'Website context unavailable',target:'website',severity:'blocking'});
    if(!references.discovery)attention.push({kind:'missing-discovery',label:'Discovery reference unavailable',target:'discovery',severity:'blocking'});
    if(!references.strategy)attention.push({kind:'missing-strategy',label:'Strategy reference unavailable',target:'strategy',severity:'blocking'});
    for(const key of references.strategy?.staleFields||[])attention.push({kind:'stale-strategy',label:`Strategy input update available: ${key}`,target:'strategy',referenceId:key,severity:'attention'});
    for(const item of staleRecommendations)attention.push({kind:'stale-recommendation',label:`Stale recommendation: ${item.title}`,target:'recommendations',referenceId:item.id,severity:'attention'});
    for(const item of unresolvedConversations)attention.push({kind:'unresolved-conversation',label:item.messages[0]?.body||'Unresolved conversation',target:'review',referenceId:item.id,severity:item.status==='waiting-on-rally'?'blocking':'attention'});
    for(const item of blockedTasks)attention.push({kind:'blocked-task',label:item.title,target:'tasks',referenceId:item.id,severity:'blocking'});
    if(activeReview&&!activeReview.questionnaireSummary.requiredComplete)attention.push({kind:'review-questions',label:'Required review questions remain',target:'review',referenceId:activeReview.id,severity:'blocking'});
    if(activeReview&&activeReview.summary.ready&&activeReview.questionnaireSummary.requiredComplete&&!activeReview.currentApproval)attention.push({kind:'awaiting-approval',label:'Review is ready for approval',target:'review',referenceId:activeReview.id,severity:'attention'});
    let phase='build';if(approvedReview)phase='approved';else if(activeReview||references.reviews.length)phase='review';else if(references.discovery?.progress.state!=='completed')phase='discovery';else if(references.strategy?.progress.state!=='ready')phase='strategy';else if(!references.recommendations.length||references.recommendations.some(item=>['proposed','stale'].includes(item.status)))phase='recommendations';
    let nextAction;if(['on-hold','archived'].includes(value.status))nextAction={kind:'paused',label:value.status==='archived'?'Project archived':'Project on hold',reason:'Resume the Project lifecycle before continuing operational work.',target:'project',priority:'normal'};else if(!references.website)nextAction={kind:'restore-context',label:'Restore Website context',reason:'The referenced Website is unavailable.',target:'website',priority:'blocking'};else if(phase==='discovery')nextAction={kind:'complete-discovery',label:'Complete Discovery',reason:'Required Discovery answers remain.',target:'discovery',referenceId:value.discoveryResponseSetId,priority:'high'};else if(phase==='strategy')nextAction={kind:'resolve-strategy',label:'Resolve Strategy decisions',reason:'Strategy is not ready for downstream work.',target:'strategy',referenceId:value.strategyId,priority:'high'};else if(phase==='recommendations')nextAction={kind:'review-recommendations',label:staleRecommendations.length?'Refresh recommendations':'Review recommendations',reason:staleRecommendations.length?'Strategy or Discovery inputs changed.':'Strategy is ready for recommendations.',target:'recommendations',priority:'high'};else if(phase==='review'){if(activeReview?.summary.unresolved)nextAction={kind:'resolve-review-conversations',label:'Resolve review conversations',reason:`${activeReview.summary.unresolved} conversation${activeReview.summary.unresolved===1?'':'s'} remain unresolved.`,target:'review',referenceId:activeReview.id,priority:'high'};else if(activeReview&&!activeReview.questionnaireSummary.requiredComplete)nextAction={kind:'complete-review-questions',label:'Complete required review questions',reason:'Approval evidence is incomplete.',target:'review',referenceId:activeReview.id,priority:'high'};else if(activeReview&&!activeReview.currentApproval)nextAction={kind:'approve-website',label:'Approve Website',reason:'The active review is ready for an explicit approval decision.',target:'review',referenceId:activeReview.id,priority:'high'};else nextAction={kind:'start-review',label:'Start Review',reason:'A formal review is the next operational checkpoint.',target:'review',priority:'normal'};}else if(phase==='approved')nextAction={kind:'approved',label:'Website approved',reason:'The current Review checkpoint has explicit approval.',target:'review',referenceId:approvedReview.id,priority:'normal'};else nextAction={kind:'continue-build',label:'Continue Website editing',reason:'Applied decisions are ready for Website work and review preparation.',target:'website',priority:'normal'};
    return{project:clone(value),references,phase,nextAction,attention,counts:{tasks:references.tasks.length,blockedTasks:blockedTasks.length,unresolvedConversations:unresolvedConversations.length,recommendations:references.recommendations.length,reviews:references.reviews.length}};};
  const api={statuses:STATUSES,subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);},getState(){return{projects:clone(projects),order:[...order],selectedId};},get(id){return clone(project(id));},list(){return order.map(id=>api.summary(id));},resolve,summary:derive,select(id){project(id);selectedId=id;notify();},create({name,websiteId,discoveryResponseSetId=null,strategyId=null,description='',createdBy='rally-staff'}){const label=String(name||'').trim();if(!label)throw new Error('Project name is required');const id=`project-${Date.now().toString(36)}-${++sequence}`,now=new Date().toISOString();projects[id]={id,name:label,description:String(description),status:'active',websiteId,discoveryResponseSetId,strategyId,createdAt:now,updatedAt:now,createdBy:actor(createdBy)};order.push(id);selectedId=id;notify();return id;},setStatus(id,status){if(!STATUSES.includes(status))throw new Error(`Unsupported Project status: ${status}`);const value=project(id);value.status=status;value.updatedAt=new Date().toISOString();notify();return clone(value);}};
  if(seed){const document=documentStore.getState(),discoveryResponseSetId=discoveryStore.ensureCurrent(),strategyId=strategyStore.ensureCurrent();api.create({name:'Northstar Advisory Website',description:'Studio 4 working Website project.',websiteId:document.website.id,discoveryResponseSetId,strategyId});}
  return api;
}
