export function assignmentSelect(teamStore,currentId,onChange,label='Owner'){
  const field=document.createElement('label'),select=document.createElement('select');field.textContent=label;select.setAttribute('aria-label',label);select.append(new Option('Unassigned',''));
  for(const member of teamStore.list())if(member.status==='active'||member.id===currentId){const option=new Option(`${member.name}${member.status==='archived'?' (archived)':''}`,member.id);option.disabled=member.status==='archived';select.append(option);}
  select.value=currentId||'';select.onchange=()=>onChange(select.value||null);field.append(select);return field;
}

export function initTeamUI({teamStore,workloads,container,domains}){
  const shell=document.createElement('section');shell.className='work-queue-workspace';shell.innerHTML='<header><div><small>Internal Rally product team · not client Contacts or authentication</small><h1>Team</h1></div><button data-close-team>Back to Projects</button></header><main><form data-add-team><h2>Add Team member</h2><label>Name<input name="name" required></label><label>Email<input name="email" type="email"></label><label>Role<input name="role"></label><button>Add member</button></form><div data-team-members></div></main>';document.body.append(shell);
  const toggle=document.createElement('button');toggle.textContent='Team';container.append(toggle);toggle.onclick=()=>{shell.classList.add('open');render();};shell.querySelector('[data-close-team]').onclick=()=>shell.classList.remove('open');
  shell.querySelector('form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;teamStore.create(Object.fromEntries([...form.querySelectorAll('input')].map(input=>[input.name,input.value])));form.reset();};
  function render(){shell.querySelector('[data-team-members]').replaceChildren(...workloads.list().map(work=>{const {member}=work,row=document.createElement('article');row.className='team-item';const form=document.createElement('form'),heading=document.createElement('h2');heading.textContent=`${member.name} · ${member.status}`;form.append(heading);for(const key of ['name','email','role']){const field=document.createElement('label'),input=document.createElement('input');field.textContent=key;input.name=key;input.value=member[key];input.required=key==='name';input.type=key==='email'?'email':'text';field.append(input);form.append(field);}const save=document.createElement('button');save.textContent='Save member';save.type='button';form.append(save);const saveMember=()=>{if(form.reportValidity())teamStore.update(member.id,Object.fromEntries([...form.querySelectorAll('input')].map(input=>[input.name,input.value])));};save.onclick=saveMember;form.onsubmit=event=>{event.preventDefault();saveMember();};const summary=document.createElement('p');summary.textContent=`${work.openTasks.length} open Tasks · ${work.readyCheckpoints.length} ready manual checkpoints · ${work.actionableItems.length} actionable queue items · ${work.highPriorityItems.length} high priority · ${work.ledProjects.length} led Projects`;const details=document.createElement('ul');for(const item of [...work.openTasks,...work.readyCheckpoints,...work.ledProjects.map(value=>value.project)]){const li=document.createElement('li');li.textContent=item.title||item.name;details.append(li);}const archive=document.createElement('button');archive.textContent=member.status==='active'?'Archive member':'Unarchive member';archive.onclick=()=>teamStore.setStatus(member.id,member.status==='active'?'archived':'active');const note=document.createElement('small');note.textContent='Archiving preserves existing ownership; it never unassigns work. Workload is derived, not capacity planning.';row.append(form,summary,details,archive,note);return row;}));}
  for(const domain of domains)domain.subscribe(render);render();return{render};
}
