const clone=value=>structuredClone(value);
const priorityRank={high:0,normal:1,low:2};

// A read-only projection: no independently mutable queue records or completion API.
export function createWorkQueue({projectStore,roadmapStore,taskStore,conversationStore,teamStore}){
  function projectItems(summary){
    const project=summary.project,items=new Map(),available=!!summary.references.website;
    const add=(key,item,provenance)=>{const id=`queue:${project.id}:${key}`,existing=items.get(id);if(existing){existing.provenance.push(provenance);if(priorityRank[item.priority]<priorityRank[existing.priority])existing.priority=item.priority;return;}items.set(id,{id,projectId:project.id,organizationId:project.organizationId,sourceId:null,referenceId:null,status:'actionable',contextAvailable:available,...item,provenance:[provenance]});};
    const provenance=(sourceType,sourceId,kind)=>({sourceType,sourceId,kind});
    const action=summary.nextAction;
    const actionKey=action=>action.kind==='assign-website'?'setup':action.kind==='complete-review-questions'?`review-questions:${action.referenceId}`:action.kind==='approve-website'?`approval:${action.referenceId}`:`action:${action.kind}:${action.referenceId||action.target}`;
    if(!['paused','approved'].includes(action.kind))add(actionKey(action),{sourceType:'project',kind:action.kind,title:action.label,why:action.reason,priority:action.priority==='blocking'?'high':'normal',target:action.target,referenceId:action.referenceId||null},provenance('project-next-action',project.id,action.kind));
    const taskState=taskStore.getState(),conversationState=conversationStore.getState();
    const tasks=taskState.order.map(id=>taskState.tasks[id]).filter(item=>project.websiteId&&item.websiteId===project.websiteId&&item.status!=='done');
    const conversations=conversationState.order.map(id=>conversationState.conversations[id]).filter(item=>project.websiteId&&item.websiteId===project.websiteId&&item.status!=='resolved');
    for(const task of tasks)add(`task:${task.id}`,{sourceType:'task',sourceId:task.id,referenceId:task.id,kind:'task',title:task.title,why:task.status==='blocked'?'Existing Task is blocked.':'Existing Task requires execution.',priority:task.status==='blocked'?'high':'normal',target:'tasks',status:task.status,ownerId:task.assigneeId||null,actorId:task.assignedTo?.id||task.createdBy?.id||null},provenance('task',task.id,task.status));
    for(const conversation of conversations)add(`conversation:${conversation.id}`,{sourceType:'conversation',sourceId:conversation.id,referenceId:conversation.id,kind:'unresolved-conversation',title:conversation.messages[0]?.body||'Unresolved Conversation',why:conversation.status==='waiting-on-client'?'Waiting for client feedback; monitor in Review.':'Unresolved collaboration requires attention.',priority:conversation.status==='waiting-on-rally'?'high':'normal',target:'review',status:conversation.status},provenance('conversation',conversation.id,conversation.status));
    for(const attention of summary.attention){const task=attention.kind==='blocked-task',conversation=attention.kind==='unresolved-conversation',setup=['unassigned-website','unavailable-website'].includes(attention.kind),review=attention.kind==='review-questions',approval=attention.kind==='awaiting-approval',key=task?`task:${attention.referenceId}`:conversation?`conversation:${attention.referenceId}`:setup?'setup':review?`review-questions:${attention.referenceId}`:approval?`approval:${attention.referenceId}`:`attention:${attention.kind}:${attention.referenceId||attention.target}`;add(key,{sourceType:task?'task':conversation?'conversation':review||approval?'review':'attention',sourceId:attention.referenceId||null,referenceId:attention.referenceId||null,kind:attention.kind,title:attention.label,why:attention.label,priority:attention.severity==='blocking'||approval?'high':'normal',target:attention.target},provenance('project-attention',attention.referenceId||project.id,attention.kind));}
    const roadmap=roadmapStore.getForProject(project.id);for(const checkpoint of roadmap?.checkpoints||[])if(checkpoint.completionMode==='manual'&&checkpoint.status==='ready')add(`roadmap:${checkpoint.id}`,{sourceType:'roadmap',sourceId:checkpoint.id,referenceId:checkpoint.id,ownerId:checkpoint.ownerId||null,roadmapId:roadmap.roadmap.id,kind:'ready-manual-checkpoint',title:checkpoint.title,why:'Ready for explicit Rally operational completion in the Roadmap.',priority:'normal',target:'roadmap'},provenance('roadmap-checkpoint',checkpoint.id,'ready'));
    return [...items.values()].map(item=>{const suggestedOwnerId=['task','roadmap'].includes(item.sourceType)||item.ownerId?null:project.ownerId||null;return({...item,ownerId:item.ownerId||null,suggestedOwnerId,ownerSource:item.ownerId?'explicit':suggestedOwnerId?'project-default':'unassigned',ownerStatus:(item.ownerId||suggestedOwnerId)&&teamStore?teamStore.get(item.ownerId||suggestedOwnerId).status:null,status:!available&&item.target!=='project'?'unavailable':item.status,why:!available&&item.target!=='project'?`${item.why} Website context is unavailable; open Project to inspect.`:item.why});});
  }
  const api={list(filters={}){const values=projectStore.list().filter(summary=>!['archived','on-hold','completed'].includes(summary.project.status)).flatMap(projectItems);return values.filter(item=>(!filters.organizationId||item.organizationId===filters.organizationId)&&(!filters.projectId||item.projectId===filters.projectId)&&(!filters.sourceType||item.sourceType===filters.sourceType)&&(!filters.priority||item.priority===filters.priority)&&(!filters.status||item.status===filters.status)&&(!filters.ownerId||(filters.ownerId==='unassigned'?!(item.ownerId||item.suggestedOwnerId):(item.ownerId||item.suggestedOwnerId)===filters.ownerId))).sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||a.projectId.localeCompare(b.projectId)||a.id.localeCompare(b.id)).map(clone);},summary(){const items=api.list(),projectCounts={};for(const item of items)projectCounts[item.projectId]=(projectCounts[item.projectId]||0)+1;return{total:items.length,high:items.filter(item=>item.priority==='high').length,projectCounts};}};
  return api;
}
