[CmdletBinding()]
param([Parameter(Mandatory)][string]$Package,[string]$ReportPath='',[switch]$NoExitFailure)
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
$resolved=(Resolve-Path -LiteralPath $Package).Path
$failures=[Collections.Generic.List[string]]::new();$authorities=[Collections.Generic.List[string]]::new();$zip=$null
function ReadJsonEntry($archive,[string]$path,[bool]$required){$entry=$archive.GetEntry($path);if(-not$entry){if($required){$failures.Add("missing-canonical-authority:$path")};return $null};$authorities.Add($path);$reader=[IO.StreamReader]::new($entry.Open());try{$text=$reader.ReadToEnd();try{return $text|ConvertFrom-Json}catch{$failures.Add("malformed-canonical-authority:$path");return $null}}finally{$reader.Dispose()}}
try{
  $zip=[IO.Compression.ZipFile]::OpenRead($resolved)
  $root=ReadJsonEntry $zip 'framework.json' $true;$inventory=ReadJsonEntry $zip 'package-inventory.json' $true;$duplicate=ReadJsonEntry $zip 'schemas-integrity/framework.json' $false
  if($root){if([string]::IsNullOrWhiteSpace($root.version)){$failures.Add('missing-canonical-field:framework.json#version')};if([string]::IsNullOrWhiteSpace($root.package_build)){$failures.Add('missing-canonical-field:framework.json#package_build')};if([string]::IsNullOrWhiteSpace($root.release_target)){$failures.Add('missing-canonical-field:framework.json#release_target')};if($root.version-ne$root.package_build){$failures.Add('canonical-disagreement:framework.json#version!=framework.json#package_build')};if($root.PSObject.Properties['governing_framework_version']-and[string]::IsNullOrWhiteSpace($root.governing_framework_version)){$failures.Add('missing-canonical-field:framework.json#governing_framework_version')};if($root.governing_framework_version-and$root.governing_framework_version-eq$root.package_build-and$root.package_build-match'-dev\.'){$failures.Add('candidate-cannot-be-current-governor')}}
  if($root-and$inventory){if($inventory.candidate_identity-ne$root.package_build){$failures.Add('canonical-disagreement:package-inventory.json#candidate_identity!=framework.json#package_build')};if($inventory.release_target-ne$root.release_target){$failures.Add('canonical-disagreement:package-inventory.json#release_target!=framework.json#release_target')};foreach($field in @('governing_framework_version','historical_baseline_version')){if($root.PSObject.Properties[$field]-and$inventory.$field-ne$root.$field){$failures.Add("canonical-disagreement:package-inventory.json#$field!=framework.json#$field")}}}
  if($root-and$duplicate){foreach($field in @('version','package_build','release_target','governing_framework_version','historical_baseline_version')){if($root.PSObject.Properties[$field]-and$duplicate.$field-ne$root.$field){$failures.Add("canonical-disagreement:schemas-integrity/framework.json#$field!=framework.json#$field")}}}
  $identity=if($root){[string]$root.package_build}else{$null};$kind=if($identity-match'-dev\.'){'development'}elseif($identity-match'^\d+\.\d+\.\d+$'){'stable-production'}else{'unknown'};if($identity-and$kind-eq'unknown'){$failures.Add("malformed-canonical-identity:framework.json#package_build=$identity")}
  $result=[ordered]@{schema_version=1;result=$(if($failures.Count){'failed'}else{'passed'});package=(Split-Path -Leaf $resolved);package_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $resolved).Hash.ToLowerInvariant();canonical_identity=$identity;identity_kind=$kind;release_target=$(if($root){$root.release_target}else{$null});governing_framework_version=$(if($root){$root.governing_framework_version}else{$null});historical_baseline_version=$(if($root){$root.historical_baseline_version}else{$null});source_provenance_identity=$(if($inventory-and$inventory.PSObject.Properties['source_provenance_identity']){$inventory.source_provenance_identity}else{$null});canonical_authority_files=@($authorities);historical_references_authoritative=$false;failures=@($failures)}
}catch{$result=[ordered]@{schema_version=1;result='failed';package=(Split-Path -Leaf $resolved);package_sha256=$null;canonical_identity=$null;identity_kind='unknown';release_target=$null;source_provenance_identity=$null;canonical_authority_files=@($authorities);historical_references_authoritative=$false;failures=@("invalid-package:$($_.Exception.Message)")}}finally{if($zip){$zip.Dispose()}}
if($ReportPath){$parent=Split-Path -Parent $ReportPath;if($parent){New-Item -ItemType Directory -Force $parent|Out-Null};$result|ConvertTo-Json -Depth 6|Set-Content -Encoding utf8 $ReportPath};$result|ConvertTo-Json -Depth 6;if($result.result-ne'passed'-and-not$NoExitFailure){exit 1}
