[CmdletBinding()]
param([Parameter(Mandatory)][string]$Package,[Parameter(Mandatory)][string]$ExpectedSha256,[string]$ExpectedIdentity='',[string]$ExpectedVersion='',[string]$TargetFramework='',[switch]$NoExitFailure)
$ErrorActionPreference='Stop'
function Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()}
$fail=[Collections.Generic.List[string]]::new();$entries=@();$manifest=$null;$profile=$null
if(-not(Test-Path -LiteralPath $Package)){$fail.Add('package-missing')}elseif((Hash $Package)-ne$ExpectedSha256){$fail.Add('package-sha256-mismatch')}
if(-not$fail.Count){
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  try{$zip=[IO.Compression.ZipFile]::OpenRead((Resolve-Path $Package).Path);$seen=@{};foreach($entry in $zip.Entries){$path=$entry.FullName.Replace('\','/');if($path.StartsWith('/')-or$path-match'(^|/)\.\.(/|$)'){$fail.Add("unsafe-entry:$path");continue};$key=$path.ToLowerInvariant();if($seen.ContainsKey($key)){$fail.Add("duplicate-entry:$path")}else{$seen[$key]=$true};if(-not$path.EndsWith('/')){$entries+=$path}};$authorities=@($zip.Entries|Where-Object{$_.FullName.Replace('\','/')-match'^[^/]+/extension-manifest\.yaml$'});if($authorities.Count-ne1){$fail.Add("canonical-authority-count:$($authorities.Count)")}else{$reader=[IO.StreamReader]::new($authorities[0].Open());try{$manifestText=$reader.ReadToEnd()}finally{$reader.Dispose()};$manifest=[ordered]@{};foreach($name in @('extension-slug','extension-version','extension-type','package-type','entry-point')){$m=[regex]::Match($manifestText,"(?m)^$([regex]::Escape($name)):\s*`"?([^`"\r\n]*)");$manifest[$name]=$m.Groups[1].Value};$min=[regex]::Match($manifestText,'(?ms)^framework-compatibility:\s*.*?^\s+minimum:\s*"?([^"\r\n]+)').Groups[1].Value;$manifest.framework_minimum=$min;$root=($authorities[0].FullName.Replace('\','/')-split'/')[0];if("$root/$($manifest.'entry-point')"-notin$entries){$fail.Add('entry-point-missing')};if($manifest.'package-type'-ne'complete-distribution'){$fail.Add('package-type-invalid')};if($ExpectedIdentity-and$manifest.'extension-slug'-ne$ExpectedIdentity){$fail.Add('identity-mismatch')};if($ExpectedVersion-and$manifest.'extension-version'-ne$ExpectedVersion){$fail.Add('version-mismatch')};if($TargetFramework-and$min){try{if([version]$TargetFramework.Split('-')[0]-lt[version]$min){$fail.Add('framework-applicability-mismatch')}}catch{$fail.Add('framework-applicability-invalid')}};$profiles=@($zip.Entries|Where-Object{$_.FullName.Replace('\','/')-match'^[^/]+/profile\.json$'});if($profiles.Count-gt1){$fail.Add('duplicate-profile-authority')}elseif($profiles.Count-eq1){$reader=[IO.StreamReader]::new($profiles[0].Open());try{$profile=$reader.ReadToEnd()|ConvertFrom-Json}finally{$reader.Dispose()};if($profile.slug-ne$manifest.'extension-slug'-or$profile.version-ne$manifest.'extension-version'-or$profile.package_type-ne'complete-distribution'){$fail.Add('profile-authority-mismatch')}};if(-not(@($entries|Where-Object{$_-match'/(?:package-manifest\.md|docs/extensions/distribution-contents\.md)$'}).Count)){$fail.Add('distribution-inventory-authority-missing')}}
  }catch{$fail.Add("archive-invalid:$($_.Exception.Message)")}finally{if($zip){$zip.Dispose()}}
}
$result=[ordered]@{schema_version=1;result=$(if($fail.Count){'failed'}else{'passed'});package=[IO.Path]::GetFileName($Package);sha256=$(if(Test-Path $Package){Hash $Package}else{$null});identity=$(if($manifest){$manifest.'extension-slug'}else{$null});version=$(if($manifest){$manifest.'extension-version'}else{$null});extension_type=$(if($manifest){$manifest.'extension-type'}else{$null});package_type=$(if($manifest){$manifest.'package-type'}else{$null});framework_minimum=$(if($manifest){$manifest.framework_minimum}else{$null});entry_count=$entries.Count;authority='extension-manifest.yaml';migration_decision='preserve-authenticated-installed-lock';failures=@($fail)};$result|ConvertTo-Json -Depth 8;if($fail.Count-and-not$NoExitFailure){exit 1}
