[CmdletBinding()]
param([string]$RepositoryRoot='',[string]$PlanPath='framework-adoption-plan.json',[string]$ReportPath='',[switch]$NoExitFailure)
$ErrorActionPreference='Stop';if(-not$RepositoryRoot){$RepositoryRoot=Split-Path -Parent $PSScriptRoot};$RepositoryRoot=(Resolve-Path $RepositoryRoot).Path;$planFile=if([IO.Path]::IsPathRooted($PlanPath)){$PlanPath}else{Join-Path $RepositoryRoot $PlanPath};$fail=[Collections.Generic.List[string]]::new()
function HashBytes([byte[]]$Bytes){$hash=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($hash.ComputeHash($Bytes))).Replace('-','').ToLowerInvariant()}finally{$hash.Dispose()}}
if(-not(Test-Path $planFile)){$fail.Add('adoption-plan-missing');$plan=$null}else{$plan=Get-Content -Raw $planFile|ConvertFrom-Json}
if($plan){foreach($write in @($plan.managed_writes)){$path=Join-Path $RepositoryRoot $write.path;if(-not(Test-Path $path)){$fail.Add("managed-path-missing:$($write.path)");continue};$expected=$write.content_sha256;$actual=HashBytes([IO.File]::ReadAllBytes($path));if($actual-ne$expected){$fail.Add("managed-path-drift:$($write.path)")}};foreach($remove in @($plan.managed_removals)){if(Test-Path(Join-Path $RepositoryRoot $remove)){$fail.Add("managed-removal-drift:$remove")}}}
$installed=& (Join-Path $PSScriptRoot 'validate-installed-framework.ps1') -RepositoryRoot $RepositoryRoot -NoExitFailure|ConvertFrom-Json;if($installed.result-ne'passed'){foreach($failure in @($installed.failures)){$fail.Add($failure)}}
$result=[ordered]@{schema_version=1;result=$(if($fail.Count){'failed'}else{'passed'});plan_sha256=$(if($plan){$plan.plan_sha256}else{$null});validation_state=$(if($fail.Count){'blocked'}else{'completed'});failures=@($fail)}
if($ReportPath){$out=if([IO.Path]::IsPathRooted($ReportPath)){$ReportPath}else{Join-Path $RepositoryRoot $ReportPath};New-Item -ItemType Directory -Force (Split-Path $out)|Out-Null;$result|ConvertTo-Json -Depth 10|Set-Content -Encoding utf8 $out};$result|ConvertTo-Json -Depth 10;if($fail.Count-and-not$NoExitFailure){exit 1}
