import test from 'node:test';
import assert from 'node:assert/strict';
import { createComponentRegistry } from '../component-registry.js';
import { orderedInstances, validateStudioState } from '../model.js';
import { createStudioStore } from '../state-store.js';
import { seedState } from '../seed.js';
import { componentDefinitions } from '../components.js';

test('website page and ordered component references are structurally valid',()=>{assert.deepEqual(validateStudioState(seedState),[]);assert.deepEqual(orderedInstances(seedState).map(item=>item.id),['instance-hero','instance-services','instance-cta'])});
test('registry resolves definitions independently from instance content',()=>{const registry=createComponentRegistry().register({type:'example',contentSchema:['title'],render:content=>content.title});assert.equal(registry.resolve('example').render({title:'Reusable content'}),'Reusable content');assert.throws(()=>registry.resolve('missing'),/Unknown component type/)});
test('global settings update atomically and notify subscribers',()=>{const store=createStudioStore(seedState);let observed;store.subscribe(state=>{observed=state.designSettings});store.updateDesignSettings({primaryColor:'#ff0066',radius:24});assert.equal(observed.primaryColor,'#ff0066');assert.equal(observed.radius,24);assert.match(store.exportSnapshot(),/"componentInstanceIds"/)});
test('canvas and Explorer share one selected instance identity',()=>{const store=createStudioStore(seedState);store.selectComponent('instance-services');assert.equal(store.getState().workspace.selectedComponentId,'instance-services');store.setMode('preview');assert.equal(store.getState().workspace.selectedComponentId,null);assert.equal(store.getState().workspace.mode,'preview');store.setMode('edit');assert.equal(store.getState().workspace.mode,'edit')});
test('inline and panel editors share the structured content update path',()=>{const store=createStudioStore(seedState);store.updateComponentContent('instance-hero','heading','A clearer heading');store.updateComponentContent('instance-services','items.0.title','Updated service');assert.equal(store.getState().componentInstances['instance-hero'].content.heading,'A clearer heading');assert.equal(store.getState().componentInstances['instance-services'].content.items[0].title,'Updated service');assert.throws(()=>store.updateComponentContent('missing','heading','No'),/Unknown component instance/)});
test('structural order mutations are centralized and undoable',()=>{const store=createStudioStore(seedState);store.moveComponent('instance-cta',0);assert.equal(store.getState().page.componentInstanceIds[0],'instance-cta');store.undoLastStructuralAction();assert.deepEqual(store.getState().page.componentInstanceIds,seedState.page.componentInstanceIds)});
test('registry defaults insert unique instances and duplicate content independently',()=>{const store=createStudioStore(seedState);const definition=componentDefinitions.find(item=>item.type==='cta');const added=store.insertComponent(definition,1);const copy=store.duplicateComponent(added);assert.notEqual(added,copy);store.updateComponentContent(copy,'heading','Independent copy');assert.notEqual(store.getState().componentInstances[added].content.heading,'Independent copy');assert.equal(store.getState().page.componentInstanceIds[1],added)});
test('hide show delete and one-level undo preserve structured content',()=>{const store=createStudioStore(seedState),before=store.getState().componentInstances['instance-services'].content;store.setComponentHidden('instance-services',true);assert.equal(store.getState().componentInstances['instance-services'].hidden,true);store.setComponentHidden('instance-services',false);assert.deepEqual(store.getState().componentInstances['instance-services'].content,before);store.deleteComponent('instance-services');assert.equal(store.getState().componentInstances['instance-services'],undefined);store.undoLastStructuralAction();assert.deepEqual(store.getState().componentInstances['instance-services'].content,before)});
test('variant selection validates definition membership and preserves content',()=>{const store=createStudioStore(seedState),hero=componentDefinitions.find(item=>item.type==='hero'),before=store.getState().componentInstances['instance-hero'].content;store.setComponentVariant('instance-hero',hero,'split');store.setComponentVariant('instance-hero',hero,'editorial');assert.deepEqual(store.getState().componentInstances['instance-hero'].content,before);assert.equal(store.getState().componentInstances['instance-hero'].variantId,'editorial');assert.throws(()=>store.setComponentVariant('instance-hero',hero,'unknown'),/Unknown variant/)});
test('insert uses default variant and duplicate preserves variant independently',()=>{const store=createStudioStore(seedState),hero=componentDefinitions.find(item=>item.type==='hero'),added=store.insertComponent(hero,0);assert.equal(store.getState().componentInstances[added].variantId,hero.defaultVariantId);store.setComponentVariant(added,hero,'split');const copy=store.duplicateComponent(added);assert.equal(store.getState().componentInstances[copy].variantId,'split');store.setComponentVariant(copy,hero,'editorial');assert.equal(store.getState().componentInstances[added].variantId,'split')});
test('registry normalizes single-variant definitions and rejects invalid defaults',()=>{const registry=createComponentRegistry().register({type:'single',render:()=>null});assert.equal(registry.resolveVariant('single').id,'default');assert.throws(()=>createComponentRegistry().register({type:'bad',defaultVariantId:'missing',variants:[{id:'only',render:()=>null}]}),/Unknown default variant/)});
