import test from 'node:test';
import assert from 'node:assert/strict';
import {createOperationsContext,deriveOperationsHome,ownershipLabel} from '../operations-context.js';
import {createStudioStore} from '../state-store.js';
import {seedState} from '../seed.js';
import {createTeamStore,createTeamWorkloads} from '../team-store.js';
import {createConversationStore} from '../conversation-store.js';
import {createTaskStore} from '../task-store.js';
import {createDiscoveryStore} from '../discovery-store.js';
import {createStrategyStore} from '../strategy-store.js';
import {createReviewSessionStore} from '../review-session-store.js';
import {createRecommendationStore} from '../recommendation-store.js';
import {createOrganizationStore} from '../organization-store.js';
import {createProjectStore} from '../project-store.js';
import {createRoadmapStore} from '../roadmap-store.js';
import {createWorkQueue} from '../work-queue.js';
import {createLibraryRegistry} from '../library-registry.js';
import {createComponentRegistry} from '../component-registry.js';
import {componentDefinitions} from '../components.js';
import {librarySeeds} from '../library-seeds.js';

function fixture(){const store=createStudioStore(seedState),teamStore=createTeamStore(),conversationStore=createConversationStore(store),taskStore=createTaskStore(store,conversationStore,teamStore),discoveryStore=createDiscoveryStore(store),strategyStore=createStrategyStore(store,discoveryStore),reviewSessionStore=createReviewSessionStore(store,conversationStore),organizationStore=createOrganizationStore(),library=createLibraryRegistry(),componentRegistry=createComponentRegistry();librarySeeds.forEach(value=>library.register(value));componentDefinitions.forEach(value=>componentRegistry.register(value));const recommendationStore=createRecommendationStore({documentStore:store,discoveryStore,strategyStore,library,componentRegistry}),projectStore=createProjectStore({documentStore:store,teamStore,conversationStore,taskStore,discoveryStore,strategyStore,reviewSessionStore,organizationStore,recommendationStore}),roadmapStore=createRoadmapStore({projectStore,teamStore}),queue=createWorkQueue({projectStore,roadmapStore,taskStore,conversationStore,teamStore}),workloads=createTeamWorkloads({projectStore,roadmapStore,taskStore,teamStore,queue}),navigation=createOperationsContext({projectStore,taskStore,conversationStore,reviewSessionStore});return{store,teamStore,conversationStore,taskStore,discoveryStore,strategyStore,reviewSessionStore,organizationStore,projectStore,roadmapStore,queue,workloads,navigation};}

test('Monday morning home queue Project Discovery return advances shared process without history mutation',()=>{const f=fixture(),before=f.store.exportSnapshot(),view=deriveOperationsHome(f);assert.equal(view.activeProjects,2);assert.equal(view.blockedProjects,1);const action=view.topItems.find(item=>item.projectId==='project-northstar');f.navigation.project(action.projectId,{origin:'queue'});const roadmap=f.roadmapStore.apply(action.projectId);f.navigation.source(action);assert.equal(f.navigation.get().surface,'website');assert.equal(f.navigation.get().origin,'queue');const project=f.projectStore.get(action.projectId);for(const question of f.discoveryStore.definition.questions.filter(item=>item.required))f.discoveryStore.respond(project.discoveryResponseSetId,question.id,question.type==='multi-choice'?[question.choices[0]]:question.choices?.[0]||'Complete');assert.equal(f.navigation.returnProject(),action.projectId);assert.equal(f.projectStore.summary(action.projectId).phase,'strategy');assert.equal(f.roadmapStore.get(roadmap).currentCheckpoint.sourceCheckpointId,'discovery-reviewed');assert.ok(f.queue.list().some(item=>item.sourceType==='roadmap'));assert.ok(!f.queue.list().some(item=>item.kind==='complete-discovery'));assert.equal(f.store.exportSnapshot(),before);assert.equal(f.store.getHistory().entries.length,0);});

test('Summit Project switching replaces context and rejects every loaded Northstar domain handoff',()=>{const f=fixture();f.navigation.project('project-northstar',{origin:'queue'});f.navigation.source({target:'discovery'});f.navigation.project('project-summit');assert.equal(f.navigation.get().websiteId,null);assert.equal(f.navigation.get().organizationId,'organization-summit');for(const target of ['website','discovery','strategy','recommendations','review','tasks'])assert.throws(()=>f.navigation.source({target}),/no available Website/);assert.equal(f.navigation.get().surface,'project');assert.equal(f.projectStore.get('project-summit').websiteId,null);assert.equal(f.projectStore.summary('project-summit').references.discovery,null);assert.equal(f.store.getHistory().entries.length,0);});

test('Team workload to exact Task queue source retains identity status and archived assignment clarity',()=>{const f=fixture(),conversation=f.conversationStore.create({pageId:'page-home',body:'Fix header'}),task=f.taskStore.createFromConversation(conversation,{assigneeId:'team-designer'});f.taskStore.setStatus(task,'blocked');const item=f.queue.list({ownerId:'team-designer'}).find(item=>item.sourceId===task);f.navigation.project(item.projectId,{origin:'queue'});f.navigation.source(item);assert.equal(f.navigation.get().referenceId,task);assert.equal(f.workloads.list().find(item=>item.member.id==='team-designer').openTasks.length,1);f.taskStore.update(task,{assigneeId:'team-builder'});assert.equal(f.queue.list({ownerId:'team-builder'}).find(item=>item.sourceId===task).id,item.id);assert.equal(f.taskStore.get(task).status,'blocked');f.teamStore.setStatus('team-builder','archived');assert.match(ownershipLabel(f.teamStore,'team-builder'),/Assigned.*archived/);assert.equal(f.queue.list({ownerId:'team-builder'}).find(item=>item.sourceId===task).ownerStatus,'archived');f.taskStore.setStatus(task,'done');assert.ok(!f.queue.list().some(item=>item.sourceId===task));assert.equal(f.workloads.list().find(item=>item.member.id==='team-builder').openTasks.length,0);});

test('Exact source checks reject unknown foreign and unavailable anchors before changing navigation',()=>{const f=fixture(),conversation=f.conversationStore.create({pageId:'page-home',componentInstanceId:'instance-hero',body:'Anchor'}),task=f.taskStore.createFromConversation(conversation);f.navigation.project('project-northstar');const before=f.navigation.get();assert.throws(()=>f.navigation.source({target:'discovery',referenceId:'foreign-discovery'}),/unavailable/);assert.throws(()=>f.navigation.source({target:'strategy',referenceId:'foreign-strategy'}),/unavailable/);assert.throws(()=>f.navigation.source({target:'tasks',referenceId:'missing'}),/Unknown task/);f.store.deleteComponent('instance-hero');assert.throws(()=>f.navigation.source({target:'tasks',referenceId:task}),/unavailable/);assert.throws(()=>f.navigation.source({target:'review',kind:'unresolved-conversation',referenceId:conversation}),/unavailable/);assert.deepEqual(f.navigation.get(),before);});

test('Organization multiple Contacts and Projects keep return relationship isolated',()=>{const f=fixture(),contact=f.organizationStore.createContact('organization-summit',{name:'Second contact'}),second=f.projectStore.create({organizationId:'organization-summit',name:'Second engagement'});f.navigation.organization('organization-summit');assert.equal(f.navigation.get().projectId,null);f.navigation.project(second,{origin:'organization'});assert.equal(f.navigation.get().organizationId,'organization-summit');assert.equal(f.organizationStore.listContacts('organization-summit').some(item=>item.id===contact),true);assert.equal(f.projectStore.list({organizationId:'organization-summit'}).length,2);f.navigation.directWebsite();assert.equal(f.navigation.returnProject(),null);assert.equal(f.navigation.get().projectId,null);assert.equal(f.store.getHistory().entries.length,0);});

test('Project suggested ownership changes neither Task nor checkpoint assignment or navigation state',()=>{const f=fixture(),roadmap=f.roadmapStore.apply('project-northstar'),manual=f.roadmapStore.get(roadmap).checkpoints.find(item=>item.completionMode==='manual'),task=f.taskStore.createFromConversation(f.conversationStore.create({pageId:'page-home',body:'Separate'}),{assigneeId:'team-builder'});f.roadmapStore.setOwner(roadmap,manual.id,'team-designer');f.navigation.project('project-northstar');const before=f.navigation.get();f.projectStore.setOwner('project-northstar','team-lead');assert.match(ownershipLabel(f.teamStore,'team-lead',{suggested:true}),/Suggested/);assert.equal(f.taskStore.get(task).assigneeId,'team-builder');assert.equal(f.roadmapStore.get(roadmap).checkpoints.find(item=>item.id===manual.id).ownerId,'team-designer');assert.deepEqual(f.navigation.get(),before);});
