import test from 'node:test';
import assert from 'node:assert/strict';
import {createTeamStore,createTeamWorkloads} from '../team-store.js';
import {createStudioStore} from '../state-store.js';
import {seedState} from '../seed.js';
import {createConversationStore} from '../conversation-store.js';
import {createTaskStore} from '../task-store.js';
import {createRoadmapStore} from '../roadmap-store.js';
import {createWorkQueue} from '../work-queue.js';

test('Team stable CRUD isolates identity and centralizes active assignment validation',()=>{const team=createTeamStore(),id=team.create({name:'Taylor',email:'t@example.test',role:'Design'}),before=team.get(id);team.update(id,{name:'Taylor Updated'});assert.equal(team.get(id).createdAt,before.createdAt);assert.equal(team.get(id).id,id);assert.throws(()=>team.create({name:' '}),/required/);assert.throws(()=>team.validateAssignment('client'),/Unknown/);team.setStatus(id,'archived');assert.throws(()=>team.validateAssignment(id),/Archived/);assert.equal(team.validateAssignment(id,id),id);assert.equal(team.validateAssignment(null),null);team.setStatus(id,'active');assert.equal(team.validateAssignment(id),id);assert.equal(team.get(id).password,undefined);});

test('Task Team assignment retains actors and survives archive without lifecycle or history cascade',()=>{const team=createTeamStore(),store=createStudioStore(seedState),comments=createConversationStore(store),tasks=createTaskStore(store,comments,team),conversation=comments.create({pageId:'page-home',body:'Fix layout',author:'client'}),id=tasks.createFromConversation(conversation,{assignedTo:'rally-staff',assigneeId:'team-designer'}),before=tasks.get(id);team.setStatus('team-designer','archived');assert.equal(tasks.get(id).assigneeId,'team-designer');assert.throws(()=>tasks.createFromConversation(conversation,{assigneeId:'team-designer'}),/Archived/);assert.throws(()=>tasks.update(id,{title:'must not apply',assigneeId:'missing'}),/Unknown/);assert.equal(tasks.get(id).title,before.title);tasks.update(id,{assigneeId:'team-builder'});assert.equal(tasks.get(id).assignedTo.id,'rally-staff');assert.equal(tasks.get(id).createdBy.id,'local-user');assert.equal(tasks.get(id).status,'todo');tasks.update(id,{assigneeId:null});assert.equal(tasks.get(id).assigneeId,null);assert.equal(comments.get(conversation).status,'open');assert.equal(store.getHistory().entries.length,0);});

function fixture(){const team=createTeamStore(),store=createStudioStore(seedState),comments=createConversationStore(store),tasks=createTaskStore(store,comments,team),project={id:'p',organizationId:'org',websiteId:seedState.website.id,ownerId:'team-lead',status:'active'},summary=()=>({project:structuredClone(project),references:{website:store.getState().website,discovery:{progress:{state:'completed'}},strategy:null,reviews:[],recommendations:[]},nextAction:{kind:'complete-discovery',label:'Discovery',target:'discovery',priority:'high'},attention:[]}),projects={get:()=>structuredClone(project),summary,list:()=>[summary()]},roadmaps=createRoadmapStore({projectStore:projects,teamStore:team}),queue=createWorkQueue({projectStore:projects,roadmapStore:roadmaps,taskStore:tasks,conversationStore:comments,teamStore:team});return{team,store,comments,tasks,project,projects,roadmaps,queue};}

test('Manual ownership is independent of completion actor and derived conditions',()=>{const f=fixture(),id=f.roadmaps.apply('p'),view=f.roadmaps.get(id),manual=view.checkpoints.find(item=>item.sourceCheckpointId==='discovery-reviewed');assert.equal(manual.status,'ready');assert.throws(()=>f.roadmaps.setOwner(id,view.checkpoints[0].id,'team-lead'),/Derived/);f.roadmaps.setOwner(id,manual.id,'team-builder');f.team.setStatus('team-builder','archived');assert.equal(f.roadmaps.get(id).checkpoints.find(item=>item.id===manual.id).ownerId,'team-builder');f.roadmaps.completeManual(id,manual.id,{completedBy:'rally-staff'});let item=f.roadmaps.get(id).checkpoints.find(item=>item.id===manual.id);assert.equal(item.completedBy.id,'rally-staff');assert.equal(item.ownerId,'team-builder');f.roadmaps.reopenManual(id,manual.id);item=f.roadmaps.get(id).checkpoints.find(item=>item.id===manual.id);assert.equal(item.ownerId,'team-builder');assert.equal(item.completedBy,null);assert.throws(()=>f.roadmaps.setOwner(id,item.id,'missing'),/Unknown/);f.roadmaps.setOwner(id,item.id,null);assert.equal(f.store.getHistory().entries.length,0);});

test('Queue ownership precedence filters identities and workloads derive from source truth',()=>{const f=fixture(),conversation=f.comments.create({pageId:'page-home',body:'Needs work'}),task=f.tasks.createFromConversation(conversation,{assigneeId:'team-designer',assignedTo:'rally-staff'}),roadmap=f.roadmaps.apply('p'),checkpoint=f.roadmaps.get(roadmap).checkpoints.find(item=>item.sourceCheckpointId==='discovery-reviewed');f.roadmaps.setOwner(roadmap,checkpoint.id,'team-builder');f.tasks.setStatus(task,'blocked');const record=f.queue.list().find(item=>item.sourceId===task);assert.equal(record.ownerId,'team-designer');assert.equal(record.suggestedOwnerId,null);assert.equal(record.ownerSource,'explicit');assert.equal(record.actorId,'rally-staff');assert.equal(f.queue.list().find(item=>item.sourceId===conversation).suggestedOwnerId,'team-lead');assert.equal(f.queue.list({ownerId:'team-designer'}).length,1);const workloads=createTeamWorkloads({teamStore:f.team,projectStore:f.projects,taskStore:f.tasks,roadmapStore:f.roadmaps,queue:f.queue});let work=workloads.list().find(item=>item.member.id==='team-designer');assert.equal(work.openTasks.length,1);assert.equal(work.highPriorityItems.length,1);assert.equal(workloads.list().find(item=>item.member.id==='team-builder').readyCheckpoints.length,1);f.tasks.update(task,{assigneeId:'team-builder'});assert.equal(f.queue.list().find(item=>item.sourceId===task).id,record.id);f.team.setStatus('team-builder','archived');assert.equal(f.queue.list().find(item=>item.sourceId===task).ownerStatus,'archived');f.project.ownerId=null;assert.ok(f.queue.list({ownerId:'unassigned'}).length);f.tasks.setStatus(task,'done');assert.equal(workloads.list().find(item=>item.member.id==='team-builder').openTasks.length,0);});
